//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEduqzContext : DbContext
    {
        public DbEduqzContext()
            : base("name=DbEduqzContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblTeste> tblTeste { get; set; }
        public virtual DbSet<TblUsuarios> tblUsuarios { get; set; }
        public virtual DbSet<TblConcursosCalendario> tblConcursosCalendario { get; set; }
        public virtual DbSet<TblCorrecoes> tblCorrecoes { get; set; }
        public virtual DbSet<TblLeadsEduqz> tblLeadsEduqz { get; set; }
        public virtual DbSet<TblLogConsultaLeads> tblLogConsultaLeads { get; set; }
        public virtual DbSet<TblCursosCredenciados> tblCursosCredenciados { get; set; }
        public virtual DbSet<TblInstituicaoCurso> tblInstituicaoCurso { get; set; }
        public virtual DbSet<TblInstituicoes> tblInstituicoes { get; set; }
        public virtual DbSet<TblInstituicoesCredenciadas> tblInstituicoesCredenciadas { get; set; }
        public virtual DbSet<TblPerfil> tblPerfil { get; set; }
        public virtual DbSet<TblPeriodoEstudante> tblPeriodoEstudante { get; set; }
        public virtual DbSet<TblRedacoes> tblRedacoes { get; set; }
        public virtual DbSet<TblRedes> tblRedes { get; set; }
        public virtual DbSet<TblUniversidadesPROUNI> tblUniversidadesPROUNI { get; set; }
        public virtual DbSet<TblUniversidadesSISU> tblUniversidadesSISU { get; set; }
    }
}
