//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblConcursosCalendario
    {
        public int id { get; set; }
        public string tipo { get; set; }
        public string exame { get; set; }
        public Nullable<System.DateTime> data_primeira_fase { get; set; }
        public Nullable<System.DateTime> data_segunda_fase { get; set; }
    }
}
