//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCursosCredenciados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCursosCredenciados()
        {
            this.TblInstituicaoCursoes = new HashSet<TblInstituicaoCurso>();
        }
    
        public int id { get; set; }
        public Nullable<int> codigo { get; set; }
        public string nome { get; set; }
        public string grau { get; set; }
        public string modalidade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblInstituicaoCurso> TblInstituicaoCursoes { get; set; }
    }
}
