//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblInstituicoesCredenciadas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblInstituicoesCredenciadas()
        {
            this.TblInstituicaoCursoes = new HashSet<TblInstituicaoCurso>();
        }
    
        public int id { get; set; }
        public string codigo_mantenedora { get; set; }
        public string razao_social { get; set; }
        public string CNPJ { get; set; }
        public string natureza_juridica { get; set; }
        public string codigo_IES { get; set; }
        public string nome { get; set; }
        public string sigla { get; set; }
        public string rua { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string tipo { get; set; }
        public string tipo_credenciamento { get; set; }
        public Nullable<int> rede_id { get; set; }
        public string categoria_administrativa { get; set; }
        public string situacao { get; set; }
        public string CEP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblInstituicaoCurso> TblInstituicaoCursoes { get; set; }
    }
}
