//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblInstituicaoCurso
    {
        public int id { get; set; }
        public Nullable<int> codigo { get; set; }
        public string codigo_IES { get; set; }
        public Nullable<int> instituicao_id { get; set; }
        public string sigla { get; set; }
        public string nome_curso { get; set; }
        public Nullable<int> curso_id { get; set; }
        public string grau { get; set; }
        public string modalidade { get; set; }
        public Nullable<int> vagas_autorizadas { get; set; }
        public Nullable<System.DateTime> dt_inicio_funcionamento { get; set; }
        public Nullable<System.DateTime> dt_ato_criacao { get; set; }
        public string situacao { get; set; }
        public string codigo_area_OCDE_geral { get; set; }
        public string codigo_area_OCDE_especifica { get; set; }
        public string area_OCDE_especifica { get; set; }
        public string codigo_area_OCDE_detalhada { get; set; }
        public string area_OCDE_detalhada { get; set; }
        public string codigo_area_OCDE_curso { get; set; }
        public string area_OCDE_curso { get; set; }
    
        public virtual TblCursosCredenciados TblCursosCredenciado { get; set; }
        public virtual TblInstituicoesCredenciadas TblInstituicoesCredenciada { get; set; }
    }
}
