//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLeadsEduqz
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string sobrenome { get; set; }
        public string apelido { get; set; }
        public Nullable<System.DateTime> data_nascimento { get; set; }
        public string email { get; set; }
        public string genero { get; set; }
        public string renda_familiar { get; set; }
        public string cota { get; set; }
        public string qual_cota { get; set; }
        public string ddd { get; set; }
        public string telefone { get; set; }
        public string telefone_2 { get; set; }
        public string cep { get; set; }
        public string uf { get; set; }
        public string cidade { get; set; }
        public string bairro { get; set; }
        public string segmento { get; set; }
        public string ult_colegio { get; set; }
        public string serie_atual { get; set; }
        public string olimpiada { get; set; }
        public string qual_olimpiada { get; set; }
        public string intercambio { get; set; }
        public string curso_universitario_1 { get; set; }
        public string curso_universitario_2 { get; set; }
        public string quais_univers { get; set; }
        public string est_universidade { get; set; }
        public string quais_univers_part { get; set; }
        public string bolsa { get; set; }
        public string xadrez { get; set; }
        public string int_idioma { get; set; }
        public string qual_idioma { get; set; }
        public string time { get; set; }
        public string fez_enem { get; set; }
        public Nullable<double> redacao { get; set; }
        public Nullable<double> linguagens { get; set; }
        public Nullable<double> matematica { get; set; }
        public Nullable<double> natureza { get; set; }
        public Nullable<double> humanas { get; set; }
    }
}
