//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLogConsultaLeads
    {
        public int id { get; set; }
        public System.DateTime data_consulta { get; set; }
        public int num_resultados { get; set; }
        public string filtro_cursos { get; set; }
        public string filtro_ano { get; set; }
        public bool filtro_segunda_lingua { get; set; }
        public bool filtro_esporte { get; set; }
        public int filtro_nota_min { get; set; }
        public int filtro_nota_max { get; set; }
        public int universidade_id { get; set; }
    }
}
