//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRedacoes
    {
        public int id { get; set; }
        public string id_firebase { get; set; }
        public bool disponivel { get; set; }
        public bool aceitado { get; set; }
        public bool cancelado { get; set; }
        public bool concluido { get; set; }
        public Nullable<System.DateTime> data_aceitado { get; set; }
        public Nullable<System.DateTime> data_concluido { get; set; }
        public System.DateTime data_criado { get; set; }
        public Nullable<System.DateTime> data_rascunho { get; set; }
        public string url_proposta { get; set; }
        public string url_redacao { get; set; }
        public bool proposta_pdf { get; set; }
        public bool rascunho { get; set; }
        public string status { get; set; }
        public string tipo { get; set; }
        public string valor_professor { get; set; }
        public int aluno_id { get; set; }
        public Nullable<int> professor_id { get; set; }
    }
}
